debug: true
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: Sistema de Vendas - Desenvolvimento
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:db
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console